### ISSUE TITLE
Implement a useful feature to prevent detecting the adblocker

### ISSUE THREAD

**Issue by laura240406** [dusnm/ad-barricade#1]
Hey,
I wrote an adblocker too some time ago. I found a useful bug in most of the adblocker detectors:
If you start a server with an invalid certificate and redirect all websites with ads to it, it won't display the ad but the ad will be fake loaded. You can check that out [here](github.com/jakiki6/adblocker/).

It would be nice if you implement that too.

**Comment by dusnm** [comment]
That's definitely a nice idea. I'll look into it. You can also contribute to the project if you wish.
